### ISSUE TITLE
zim is unable to open certain .zim files

### ISSUE THREAD

**Issue by CKingX** [dignifiedquire/zim#13]
This file (be warned, it is 6.1 GB in size!) https://mirrors.dotsrc.org/kiwix/zim/.hidden/endless/wikipedia_en_endless_maxi_2020-07.zim works perfectly fine in Kiwix as well as Endless's own Encyclopedia but zim library is not able to read it with Out of Bounds error at parse_article_list function

**Comment by dignifiedquire** [comment]
The link unfortunately doesn't work anymore, do you have an alternative source or file that triggers this error?

**Comment by joramkuntze** [comment]
I had the same issue with the wiktionary zim Files: https://ftp.fau.de/kiwix/zim/wiktionary/. 
I tried the file from 2022-08 and received an out of bound error at parse_article_list function.

**Comment by dignifiedquire** [comment]
@jopjk thanks, I tried these two, and both extracted fine with the latest code
- [wiktionary_ru_all_maxi_2022-08.zim](https://ftp.fau.de/kiwix/zim/wiktionary/wiktionary_ru_all_maxi_2022-08.zim)         
- [wiktionary_ru_all_nopic_2022-08.zim](https://ftp.fau.de/kiwix/zim/wiktionary/wiktionary_ru_all_nopic_2022-08.zim)

**Comment by joramkuntze** [comment]
I'm sorry I didn't specify more clearly. I tried now 
[wiktionary_en_all_nopic_2022-10.zim](https://ftp.fau.de/kiwix/zim/wiktionary/wiktionary_en_all_nopic_2022-10.zim) 
as well as en_all_nopic_2022-08 and en_all_nopic_2022-05 (05 and 08 are not online anymore)
All three throw the described error.

[wiktionary_ru_all_nopic_2022-08.zim](https://ftp.fau.de/kiwix/zim/wiktionary/wiktionary_ru_all_nopic_2022-08.zim) throws no error for me as well. 

Thank you for your fast response

**Comment by dignifiedquire** [comment]
@jopjk should be fixed now, there was a bug with converting number types.
