### ISSUE TITLE
Zim does not extract contents from Stack Exchange zim files

### ISSUE THREAD

**Issue by catmaps** [dignifiedquire/zim#14]
A very nice tool! It extracts the Wikivoyage zims very nicely. However, it does not extract anything from the Stack Exchange zim files by Kiwix. (However the zim-info.exe does work on the Stack Exchange zim files.) I am running on Windows 10.  Here's what I get at CMD:

Extracting file: iot.stackexchange.com_en_all_2022-05.zim to out
Generating symlinks: true
Generating copies for links: false
Main page is mainPage
Extraction done in 0.006s
  [00:00:00] [########################################] 9491/9491 (0s)

**Comment by dignifiedquire** [comment]
Do you have a link to the `zim` file? Thanks

**Comment by dignifiedquire** [comment]
Do other `zim` files work for you? I haven't tested on windows myself, so there might be some windows specific bugs hiding.

**Comment by catmaps** [comment]
Thank you for your reply!
The zim files from Wikimedia such as Wikivoyage zim files work okay for me.
But so far none of the zim files originating from Stack Exchange have extracted.
Here is a link for a small zim file from Stack Exchange: 
https://library.kiwix.org/iot.stackexchange.com_en_all_2022-11
PS: one minor error I get from Wikivoyage extraction relates to special characters in jpg file names. Those will not extract--it just throws an error for those files because Windows does not support certain special characters in file names. However, it is no problem for me because that affects very few files in the zim.

**Comment by dignifiedquire** [comment]
This was an issue due to changes in the zim format 6.1, should be fixed on `master` now.
