### ISSUE TITLE
extract_zim does not extract all files

### ISSUE THREAD

**Issue by orionseye** [dignifiedquire/zim#6]
beautiful tool, thx for this :)
However, even extracting is fast, around 50% of the content is not extracted, tested wuth wikivoyage dump https://www.mirrorservice.org/sites/download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_maxi_2019-12.zim

I tested against zimtools/zimdump and there are missing files in 'out' folder
Any idea what it could be?

**Comment by dignifiedquire** [comment]
There are some parts of the format that this tool doesn't fully handle, as well as some archives are not fully correct. It is likely one or the other.

**Comment by orionseye** [comment]
Fastest reply on git ever :)
any debugging solution, or other hint i could make this work?
Do you plan to extend this beauty?

**Comment by dignifiedquire** [comment]
@orionseye I just merged https://github.com/dignifiedquire/zim/pull/7 which fixes some issues I have seen and makes it a little faster :) could you try it out and let me know if it helps?

**Comment by orionseye** [comment]
i will.. next week and let you know. Thank you!

**Comment by orionseye** [comment]
Un-be-liev-able :) what can i say! Just extracted and inspected the output.
So nicely, clean, well structured as html
..and i let the cli speak for itself regarding speed for extracting 138.149 files

> [root@web zim_wv]# ./target/release/extract_zim wikivoyage_en_all_maxi_2019-12.zim
> Extracting file: wikivoyage_en_all_maxi_2019-12.zim to out
> 
> Generating symlinks: true
> Generating copies for links: false
> Main page is Wikivoyage:Offline_reader_Expedition/Home_page
> 
> Extraction done in 22.999s
>   [00:00:22] [########################################] 138149/138149 (0s)
> [root@web zim_wv]#

Again, Thank you Friedel, i will play around to test the files and the paths generated, but on first sight all looks perfect. Will come back soon
This is a long needed tool :)

**Comment by orionseye** [comment]
Ok, here are 2 issues i found very quick.. before i go for sleep
a) page inner links to anchors are not valid
.html extension is missing
`out/A/London/City_of_London#See `
should be 
`out/A/London/City_of_London.html#See`

b) jpeg images are populated as jpg , so they are missing within the pages should **jpeg**
as i saw, all jpeg's are jpg's

Gute Nacht :)

**Comment by dignifiedquire** [comment]
>  jpeg images are populated as jpg , so they are missing within the pages should **jpeg**
> as i saw, all jpeg's are jpg's

Are you saying the files have the extension `.jpeg` or the links?

**Comment by dignifiedquire** [comment]
> page inner links to anchors are not valid

Are you saying the links inside the html files are missing those? I would have thought that should still work based on how browsers to resolution, but I might be wrong there.

**Comment by orionseye** [comment]
> Are you saying the files have the extension `.jpeg` or the links?

The files have extension .jpeg ..  but links are generated as .jpg (aka looking for a jpg file)

> Are you saying the links inside the html files are missing those? I would have thought that should still work based on how browsers to resolution, but I might be wrong there.

Correct, the .html extension is missing from ALL links, including (anchor) links.
I saw such behavior in zimdump, and was wondering why files are extracted without an extension .. now i understand why :)
But i don;t know how easy it is to manipulate the DOM while extracting .. to add those .html extensions to each href path in DOM.
Seems  bit tricky, since some anchors also lead to same page anchor, e.g. '#eat', '#see' without linking to another file
